### ISSUE TITLE
Рекомендация по стилям

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Mihalishcher/React-test-task#10]
```
let classCallOrder = 'call-back-order';
if (visibility) {
  classCallOrder += ' visible';
}
```
Это еще достаточно простой пример, но чтобы проще было создавать подобные классы можно использовать библиотеку classnames или clsx. Тогда получится приблизительно вот так 

```
<div className={cn('call-back-order', {visible: visibility})}> 
  ...
</div>
```

Этот не обязательно, но библиотеки интересные)

**Comment by Mihalishcher** [comment]
Done!
