### ISSUE TITLE
Раздели компоненты на stateless и stateful

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Mihalishcher/React-test-task#11]
Многие компоненты такие как `CallBackOrder.js`, `CompanyMainInfo.js`, `AddFormInstrument.js`, `InstrumentMainInfo.js`...
нужно разделить на 2 компонента, в одном оставить стейта и всю логику - это stateful компонента, второй будет отвечать только за внешний вид и это stateless

**Comment by Mihalishcher** [comment]
Done!
