### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Mihalishcher/React-test-task#17]
Если ты стараешься соблюдать структуру которую я показывал то в `pages/Company` может быть лишь папка `components` и `css`
В то же время `Company.js` у тебя по сути пустой и от него можно избавиться, точнее перенести в него то что находится в `CompanyMainInfo.js`
А из `CompanyMainInfoView.js` сделать `CompanyView.js`

И тогда у тебя в папке `pages/Company/components` останется лишь `EmployeeCard.js`

**Comment by DmitriiMelnikOnix** [comment]
То же самое и с `Home`

**Comment by DmitriiMelnikOnix** [comment]
Та и с остальными страницами

**Comment by Mihalishcher** [comment]
Спасибо. Переделал. Проверь по свободе пожалуйста.
Done!
