### ISSUE TITLE
Разбор пропсов

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Mihalishcher/React-test-task#21]
Пропсы можно разбирать прямо в параметрах функции. Так немного красивее (но это мелочь)

За то в таком случае в `CallBackOrderView` можно избавится от `return` и записать стрелочную функцию короче 
```
const CallBackOrderView = ({
  visibility, onChange, closeWindow, callOrdered, counter, phoneNumber, disabledBtn
}) => (
  <div className={cn('call-back-order', { visible: visibility })}>
    ...
  </div>
)
```

**Comment by Mihalishcher** [comment]
Eslint так разбил после --fix ) Done!
