### ISSUE TITLE
withLayout и ThemeContext

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Mihalishcher/React-test-task#24]
`withLayout` оборачивает большое количество компонентов, но в каждой обертке создается отдельный `ThemeContext.Provider` а в каждом провайдере хранятся отдельные данные, у тебя они связываются через localStorage но будут проблемы с синхронизацией разных оберток

Лучше обернуть один раз, чтобы данные правильно синхронизировались

**Comment by Mihalishcher** [comment]
Done! Moved ThemeContext to App.js
