### ISSUE TITLE
Вложеность компонентов

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Mihalishcher/React-test-task#3]
<img width="337" alt="Снимок экрана 2022-05-20 в 14 56 03" src="https://user-images.githubusercontent.com/59687966/169523221-e94c6ea3-5483-4af5-b877-5c6d6fd8886e.png">

Постарайся избавиться от подобной вложенности, так искать нужный файл очень сложно
Вот пара вариантов как это можно сделать
1. Разбить все на разные компоненты
```
...
-main-info
-- main-info.js
-- main-info.css

- company
--company.js

-side-menu
--side-menu.css
--side-menu.js
...
```

2. Это подходит если компонент сильно связаны логически (наверно этот вариант лучше подойдет)
```
-company 
--company.js
--side-menu.js
--main-info.js
--css
---main-info.css
---side-menu.css
...
```

**Comment by DmitriiMelnikOnix** [comment]
Это была старая версия кода, ты уже немного переделал, но суть +- та же

**Comment by Mihalishcher** [comment]
Done!
