### ISSUE TITLE
Регистрозависимость

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Mihalishcher/React-test-task#4]
В windows не важно как назвать файл большими буквами или маленькими, и не важно как потом импротировать. В а linux и mac os если файл называется с маленькой буквы, то и импортировать нужно с маленькой
<img width="281" alt="Снимок экрана 2022-05-20 в 15 22 27" src="https://user-images.githubusercontent.com/59687966/169527223-5bc20744-711e-492f-bd86-76208ca7dff3.png">

<img width="455" alt="Снимок экрана 2022-05-20 в 15 23 05" src="https://user-images.githubusercontent.com/59687966/169527283-892a0b8c-3cf4-47b4-b1c0-9a3b6a38c484.png">

Вот такая ошибка получается
<img width="1782" alt="Снимок экрана 2022-05-20 в 15 23 51" src="https://user-images.githubusercontent.com/59687966/169527392-d6741465-3d78-439b-8a2a-10bdc9d2e6c6.png">

**Comment by DmitriiMelnikOnix** [comment]
<img width="1792" alt="Снимок экрана 2022-05-20 в 15 24 49" src="https://user-images.githubusercontent.com/59687966/169527554-3ab0d08f-e4aa-4ebf-b149-4f1aefb64932.png">

И со всем остальным поправь)

**Comment by Mihalishcher** [comment]
Done!
